### ISSUE TITLE
Unable to connect to any servers on 1.19.2 and 1.19.0 clients

### ISSUE THREAD

**Issue by wmp71** [ViaVersion/ViaFabric#234]
### `/viaversion dump` Output

https://dump.viaversion.com/c01a109c4ef2e92e4713456178ee73907fcb807d9e8cc0acb6794a823dacab2a

### Console Error

https://paste.gg/p/anonymous/ae4d1b890fb44a059f1927dcab565d5c

### Bug Description

In 1.19.0 and 1.19.2 clients if I join any server I get an error: `com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$3383/0x000000080156c978`

Confirmed on 4.6.3 SNAPSHOT and 4.7.0 23w12a SNAPSHOT.

**THIS ISSUE HAPPENS WITHOUT \<NOCHATREPORTS> MOD TOO.**

### Steps to Reproduce

1. Open an 1.19.2 or 1.19 client with ViaFabric, ViaVersion(happens on the latest Dev version too), ViaBackwards mod.
2. Join any server.

### Expected Behavior

I can play on Minecraft servers.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Your version of ViaFabric doesn't support ViaVersion 4.6

**Comment by wmp71** [comment]
@kennytv I also tried the latest ViaFabric version, modified fabric.mod.json to make it load on 1.19, but it won't still work - noClassDefFoundError (probably because the obfuscation map is different)

If 1.19.2/1.19.0 are not officially supported anymore, is there any guide to properly compile ViaVersion from source? (I will fork ViaFabric and make it work on 1.19.0 myself)

**Comment by kennytv** [comment]
I believe one of the (alpha?) versions on modrinth should work with it
