### ISSUE TITLE
1.21.11 crash on latest build

### ISSUE THREAD

**Issue by satr14washere** [ViaVersion/ViaFabric#504]
### `/viaversion dump` Output

cant because server crashed

### Server/Client Error

```
[11:07:21] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'viafabric-mc12111' at 'com.viaversion.fabric.mc12111.ViaFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:413)
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:411)
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63)
        at knot//net.minecraft.server.Main.main(Main.java:112)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:514)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
Caused by: java.lang.NoSuchMethodError: 'int viaversion.xyz.wagyourtail.jvmdg.j10.stub.java_base.J_L_Runtime$Version.feature(viaversion.xyz.wagyourtail.jvmdg.j9.stub.java_base.J_L_Runtime$Version)'
        at knot//com.viaversion.viaversion.ViaManagerImpl.checkJavaVersion(ViaManagerImpl.java:247)
        at knot//com.viaversion.viaversion.ViaManagerImpl.onServerLoaded(ViaManagerImpl.java:176)
        at knot//com.viaversion.fabric.mc12111.ViaFabric.onInitialize(ViaFabric.java:100)
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:409)
        ... 6 more
```

### Bug Description

starting latest build for viafabric causes server crash on startup. downgrading to jdk 21 doesnt work

### Steps to Reproduce

1. use the mods and versions im using listed below
2. start server
3. crash

only way to recover is to use older builds which doesnt support the newer clients connecting (specifically geyser for bedrock players). (tested and works with build 0.4.21+163-1.14-1.21)

tried to look for latest builds from ci.viaversion.com but theyre all too old for the new clients anyways and i noticed that theres no viafabric builds there anyways.

### Additional Server Info

minecraft 1.21.11
fabric loader 0.19.3
fabric api 0.141.6
viafabric 0.4.21+173-1.14-1.21
jdk 25 temurin

more details in the following file: https://git.satr14.my.id/satr14/nix-flake/src/commit/c03945c609493a76f6dab248a08aea6b4bb10117/modules/system/homelab/mc/mc1-modded-light.nix

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity).
- [x] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by satr14washere** [comment]
issue is reproducable as im getting the same error on another host with the following mods:

<img width="571" height="488" alt="Image" src="https://github.com/user-attachments/assets/6164c293-9ed6-45aa-9126-d26fb045325c" />

even with geyser and floodgate removed im still getting the error:

<img width="1228" height="588" alt="Image" src="https://github.com/user-attachments/assets/81325a50-66fe-4d04-8a5a-ef1ae95f5f40" />

**Comment by Kichura** [comment]
You forgot to add viaversion & viabackwards to the mods list aswell.

**Comment by satr14washere** [comment]
> You forgot to add viaversion & viabackwards to the mods list aswell.

isnt viafabric the mod wrapper for the viaversion plugin? and isnt viabackwards only used when older clients try to connect to newer servers?

**Comment by Kichura** [comment]
> isnt viafabric the mod wrapper for the viaversion plugin? and isnt viabackwards only used when older clients try to connect to newer servers?

ViaVersion is bundled onto the ViaFabric jar, without it; the jar crashes. however you can add the jar regardless to override the bundled one it case it fails.

**Comment by satr14washere** [comment]
i see, thanks for the help!
also id suggest the error be handled so you can display a different error message that viaversion jar is missing. in my opinion makes things more clearer.
